name: prepare kraken report
description: 
keywords:
  - kraken2
  - report
  - krona
  - cut
tools:
  - cut:
      description: |
        Cut the second and third columns in kraken2 reports
      documentation: https://cutadapt.readthedocs.io/en/stable/index.html
      doi: DOI:10.14806/ej.17.1.200
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: The trimmed/modified fastq reads
      pattern: "*fastq.gz"
  - log:
      type: file
      description: cuatadapt log file
      pattern: "*cutadapt.log"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@kevinmenden"